export const images = {
  heroBg: "/images/hero-bg.jpg",
  successBg: "/images/success-bg.jpg",
  kellyHeadshot: "/images/kelly-headshot.jpg",
  remaxLogo: "/images/remax-logo.svg",
  areaFortLauderdale: "/images/area-fort-lauderdale.jpg",
  areaWeston: "/images/area-weston.jpg",
  areaPembrokePines: "/images/area-pembroke-pines.jpg",
  areaSWRanches: "/images/area-sw-ranches.jpg",
  areaMiami: "/images/area-miami.jpg",
  ctaBg: "/images/cta-bg.jpg",
  investmentProperty: "/images/investment-property.jpg",
  charityPhoto1: "/images/charity-1.jpg",
  charityPhoto2: "/images/charity-2.jpg",
  photographyService: "/images/service-photography.jpg",
  stagingService: "/images/service-staging.jpg",
  communicationService: "/images/service-communication.jpg",
  negotiationService: "/images/service-negotiation.jpg",
};
